In [13]:
import re
import pandas as pd

In [14]:
day_start = ["2019.12.01", "2019.12.08", "2019.12.15", "2019.12.22", "2019.12.29", "2020.01.05", "2020.01.12", "2020.01.19", "2020.01.26", "2020.02.02", "2020.02.09", "2020.02.16", "2020.02.23", "2020.03.01", "2020.03.08", "2020.03.15", "2020.03.22", "2020.03.29", "2020.04.05", "2020.04.12", "2020.04.19", "2020.04.26", "2020.05.03", "2020.05.10", "2020.05.17", "2020.05.24", "2020.05.31", "2020.06.07", "2020.06.14", "2020.06.21", "2020.06.28", "2020.07.05", "2020.07.12", "2020.07.19", "2020.07.26", "2020.08.02", "2020.08.09", "2020.08.16", "2020.08.23", "2020.08.30", "2020.09.06", "2020.09.13", "2020.09.20", "2020.09.27", "2020.10.04", "2020.10.11", "2020.10.18", "2020.10.25"]
day_end = ["2019.12.07", "2019.12.14", "2019.12.21", "2019.12.28", "2020.01.04", "2020.01.11", "2020.01.18", "2020.01.25", "2020.02.01", "2020.02.08", "2020.02.15", "2020.02.22", "2020.02.29", "2020.03.07", "2020.03.14", "2020.03.21", "2020.03.28", "2020.04.04", "2020.04.11", "2020.04.18", "2020.04.25", "2020.05.02", "2020.05.09", "2020.05.16", "2020.05.23", "2020.05.30", "2020.06.06", "2020.06.13", "2020.06.20", "2020.06.27", "2020.07.04", "2020.07.11", "2020.07.18", "2020.07.25", "2020.08.01", "2020.08.08", "2020.08.15", "2020.08.22", "2020.08.29", "2020.09.05", "2020.09.12", "2020.09.19", "2020.09.26", "2020.10.03", "2020.10.10", "2020.10.17", "2020.10.24", "2020.10.31"]

In [28]:
day_start_1 = ["2019.12.01", "2019.12.08", "2019.12.15", "2019.12.22", "2019.12.29", "2020.01.05", "2020.01.12", "2020.01.19", "2020.01.26", "2020.02.02", "2020.02.09", "2020.02.16", "2020.02.23", "2020.03.01", "2020.03.08", "2020.03.15", "2020.03.22", "2020.03.29"]
day_end_1 = ["2019.12.07", "2019.12.14", "2019.12.21", "2019.12.28", "2020.01.04", "2020.01.11", "2020.01.18", "2020.01.25", "2020.02.01", "2020.02.08", "2020.02.15", "2020.02.22", "2020.02.29", "2020.03.07", "2020.03.14", "2020.03.21", "2020.03.28", "2020.04.04"]

day_start_2 = ["2020.04.05", "2020.04.12", "2020.04.19", "2020.04.26", "2020.05.03", "2020.05.10", "2020.05.17", "2020.05.24", "2020.05.31", "2020.06.07", "2020.06.14", "2020.06.21", "2020.06.28", "2020.07.05", "2020.07.12", "2020.07.19", "2020.07.26", "2020.08.02", "2020.08.09", "2020.08.16", "2020.08.23", "2020.08.30", "2020.09.06", "2020.09.13", "2020.09.20", "2020.09.27", "2020.10.04", "2020.10.11", "2020.10.18", "2020.10.25"]
day_end_2 = ["2020.04.11", "2020.04.18", "2020.04.25", "2020.05.02", "2020.05.09", "2020.05.16", "2020.05.23", "2020.05.30", "2020.06.06", "2020.06.13", "2020.06.20", "2020.06.27", "2020.07.04", "2020.07.11", "2020.07.18", "2020.07.25", "2020.08.01", "2020.08.08", "2020.08.15", "2020.08.22", "2020.08.29", "2020.09.05", "2020.09.12", "2020.09.19", "2020.09.26", "2020.10.03", "2020.10.10", "2020.10.17", "2020.10.24", "2020.10.31"]

In [ ]:
start = day_start[0]
end = day_end[0]

start_2 = day_start[1]
end_2 = day_end[1]

test = pd.read_csv(f'naver_article/article_list_{start}_{end}.csv', encoding='utf-8-sig', usecols = ['title', 'body'])
test_2 = pd.read_csv(f'naver_article/article_list_{start_2}_{end_2}.csv', encoding='utf-8-sig', usecols = ['title', 'body'])

In [35]:
start = day_start_1[0]
end = day_end_1[0]

article_1912_2004 = pd.DataFrame(columns=['title', 'body'])

for i in range(len(day_start_1)):

    start = day_start_1[i]
    end = day_end_1[i]
    try:
        tmp = pd.read_csv(f'naver_article/article_list_{start}_{end}.csv', encoding='utf-8-sig', usecols = ['title', 'body'])
        article_1912_2004 = pd.concat([article_1912_2004, tmp], ignore_index=True)
    except:
        pass

In [36]:
article_1912_2004
article_1912_2004.to_csv('naver_article/article_1912_2004.csv', encoding='utf-8-sig', index=False)

In [37]:
start = day_start_2[0]
end = day_end_2[0]

article_2004_2010 = pd.DataFrame(columns=['title', 'body'])

for i in range(len(day_start_1)):

    start = day_start_2[i]
    end = day_end_2[i]
    try:
        tmp = pd.read_csv(f'naver_article/article_list_{start}_{end}.csv', encoding='utf-8-sig', usecols = ['title', 'body'])
        article_2004_2010 = pd.concat([article_2004_2010, tmp], ignore_index=True)
    except:
        pass

In [38]:
article_2004_2010
article_2004_2010.to_csv('naver_article/article_2004_2010.csv', encoding='utf-8-sig', index=False)

In [39]:
pd.read_csv('naver_article/article_2004_2010.csv', encoding='utf-8-sig')

,title,body
0,중앙아 키르기스서 발 묶인 교민 143명 임시항공편에 귀국,\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
1,셰프·맛집 음식도 뚝딱… 간편하고 맛도 ‘good’ [안젤라의 푸드트립],\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
2,"[뉴스인사이트] 사회적 거리두기 성적표 공개...40대는 A학점, 20대는?",\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
3,"“제주 노선 비행기, 다시 늘어난다고요?” 제주도의 고민",\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
4,[뒷북경제] 골든타임 지나가는데...기간산업 지원 뜸 들이는 정부,\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
...,...,...
7679,"항공업계 2차 타격, 기내식과 부품 '줄도산' 위기",\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
7680,[특파원 시선] 대통령의 마스크 착용과 코로나19 사망자 수의 상관관계,\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
7681,업황 개선은 언제쯤…여전히 '시계 제로'인 항공업계,\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
7682,매각 무산되면 아시아나 기안기금 지원?…기금심의회는 '신중',\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
7683,"항공업계 M&A; 무산 불똥 튄 에어로케이…국토부, 운항허가 하세월",\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...

In [40]:
pd.read_csv('naver_article/article_1912_2004.csv', encoding='utf-8-sig')

,title,body
0,"홍콩, 시위에 폐렴 위험성도 있지만...일부 항공사 항공권 할인 진행",\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
1,태국 이어 일본서도 ‘우한 폐렴’ 감염자 확인,\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
2,일본서도 ‘중국 우한 폐렴’ 환자 첫 확인,\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
3,"미국, 전세기로 우한서 자국민 철수..러시아도 자국민 대피방안 조율중",\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
4,"""러시아, 우한 등서 자국민 대피시키는 방안 중국측과 조율중""(종합)",\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
...,...,...
7827,"조원태 ""위기 극복 위한 기회 명심…뼈 깎는 자구노력 병행""",\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
7828,"조원태 한진 회장 ""국민 뜻 받들어 새로운 마음으로 출발...위기극복 총력""",\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
7829,'코로나 여파' 무안공항 개점휴업 지속…4월말 순차 재개 기대,\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
7830,‘아시아 최대 LCC’ 에어아시아마저 중단…하늘길 먹구름 짙어진다,\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...
7831,내달부터 회사채 차환 발행 지원…채권시장안정펀드도 가동,\n\n\n\n\n// flash 오류를 우회하기 위한 함수 추가\nfunction...

In [5]:
day_start = ["2019.06.30","2019.07.07","2019.07.14","2019.07.21","2019.07.28","2019.08.04","2019.08.11","2019.08.18","2019.08.25","2019.09.01","2019.09.08","2019.09.15","2019.09.22","2019.09.29","2019.10.06","2019.10.13","2019.10.20","2019.10.27","2019.11.03","2019.11.10","2019.11.17","2019.11.24"]
day_end = ["2019.07.06","2019.07.13","2019.07.20","2019.07.27","2019.08.03","2019.08.10","2019.08.17","2019.08.24","2019.08.31","2019.09.07","2019.09.14","2019.09.21","2019.09.28","2019.10.05","2019.10.12","2019.10.19","2019.10.26","2019.11.02","2019.11.09","2019.11.16","2019.11.23","2019.11.30"]

start = day_start[0]
end = day_end[0]

article_1907_1911 = pd.read_csv(f'naver_article/article_list_{start}_{end}.csv', encoding='utf-8-sig', usecols = ['title', 'body'])

for i in range(len(day_start)-1):

    start = day_start[i+1]
    end = day_end[i+1]
    try:
        tmp = pd.read_csv(f'naver_article/article_list_{start}_{end}.csv', encoding='utf-8-sig', usecols = ['title', 'body'])
        article_1907_1911 = pd.concat([article_1907_1911, tmp], ignore_index=True)
    except:
        pass

In [7]:
article_1907_1911
article_1907_1911.to_csv('naver_article/article_1907_1911.csv', encoding='utf-8-sig', index=False)

In [6]:
article_1907_1911

,title,body
0,"[자막뉴스] 美 법원, 술취해 기내난동 한국인에 실형·2억 원 배상 판결",\n\n\n\n\n\n\n 하와이 호놀룰루 공항을 이륙한 항공기안입니다. 술에 취한...
1,"미국 법원, 만취 기내 난동 한국인에 “징역 6개월·2억 원 배상”",\n\n\n\n\n\n\n [앵커]미국 하와이에서 인천으로 가는 여객기 안에서 술에...
2,[더하기 뉴스] 아이스크림 핥고 다시 제자리…도넘은 장난에 징역 위기,"\n\n\n\n\n\n\n[앵커]놓치면 아쉬운, 더하기 뉴스입니다. 이채현 기자와 ..."
3,"채형석 애경그룹 총괄부회장, 아시아나항공 인수전에 출사표 던지나",\n\n\n\n\n\n\n\t\n\t저비용항공사(LCC·Low Cost Carrie...
4,술취해 기내난동 부린 한국인 실형·2억 배상,\n\n\n\n\n\n\n (출처=뉴시스/AP) /사진=뉴시스 술에...
...,...,...
10333,이륙 직후 화염에 휩싸인 보잉 777기...美 LA국제공항 긴급회항,\n\n\n\n\n\n\n\t\n\t21일(현지 시각) 미국 캘리포니아주 로스앤젤레...
10334,"'유니클로 내복 10만장 공짜', 불매운동 주춤?…통계로 보니",\n\n\n\n동영상 뉴스\n\n\n\n\n\n\n■ '발열내복 10만장 공짜' 마...
10335,중국 진출 성공을 위해 기억해야 할 5대 키워드,"\n\n\n\n\n\n\n\t\n\t""2~4선 도시를 거점으로 중국 시장을 공략하는..."
10336,[인사이트] 성공적인 중국 비즈니스를 위해 기억할 5대 키워드,"\n\n\n\n\n\n\n\t\n\t""지난 여름 미국에 다녀왔다. 쇼핑을 하러 간 ..."
10337,미·중 무역갈등 교착…양대 FSC 화물실적 부진 지속,\n\n\n\n\n\n\n\t\n\t[아시아경제 유제훈 기자] 미ㆍ중 무역분쟁이 교...